// ── Shared Mutable Game State ───────────────────────────────────────────
export const state = {
  player: null,
  vehicles: [],
  buildings: [],
  keys: {},
  mouse: { dx: 0, dy: 0 },
  camera: { theta: 0, phi: 0.5, distance: 10 },
  isInVehicle: false,
  currentVehicle: null,
  health: 100,
  wantedLevel: 0,
  wantedDecayTimer: 0,
  lastCrimeTime: 0,
  playerVelocityY: 0,
  frameCount: 0,
  elapsedTime: 0,
  money: 0,
  gameTime: 0.5,
  npcs: [],
  trafficCars: [],
  policeCars: [],
  moneyPickups: [],
  clouds: [],
  palmTrees: [],
  ocean: null,
  neonSigns: [],
  neonPointLights: [],
  streetLights: [],
  buildingMeshes: [],
  parks: [],
  ramps: [],
  sun: null,
  ambient: null,
  hemi: null,
  isPunching: false,
  punchTimer: 0,
  isDead: false,
  deathTimer: 0,
  radioTimer: 0,
  radioVisible: false,
  hasGun: false,
  gunStore: null,
  playerBullets: [],
  policeBullets: [],
  policeOfficers: [],
  shootCooldown: 0,
  // Ragdoll
  ragdoll: { active: false, vx: 0, vy: 0, vz: 0, rotX: 0, rotZ: 0, timer: 0, lethal: false },
  // Camera shake
  cameraShake: { intensity: 0, timer: 0 },
  // Post-processing ref
  bloomPass: null,
};
