// ── Shared Mutable Game State ───────────────────────────────────────────
export const state = {
  player: null,
  vehicles: [],
  buildings: [],
  isMobile: false,
  keys: {},
  mouse: { dx: 0, dy: 0 },
  camera: { theta: 0, phi: 0.5, distance: 6 },
  isInVehicle: false,
  currentVehicle: null,
  health: 100,
  wantedLevel: 0,
  wantedDecayTimer: 0,
  lastCrimeTime: 0,
  playerVelocityY: 0,
  frameCount: 0,
  elapsedTime: 0,
  money: 0,
  gameTime: 0.5,
  npcs: [],
  trafficCars: [],
  trafficLights: [],
  trafficLightGrid: null,
  policeCars: [],
  moneyPickups: [],
  clouds: [],
  palmTrees: [],
  ocean: null,
  neonSigns: [],
  neonPointLights: [],
  streetLights: [],
  buildingMeshes: [],
  parks: [],
  ramps: [],
  sun: null,
  ambient: null,
  hemi: null,
  isPunching: false,
  punchTimer: 0,
  isDead: false,
  deathTimer: 0,
  radioTimer: 0,
  radioVisible: false,
  hasGun: false,
  gunStore: null,
  playerBullets: [],
  policeBullets: [],
  policeOfficers: [],
  shootCooldown: 0,
  // Ragdoll
  ragdoll: { active: false, vx: 0, vy: 0, vz: 0, rotX: 0, rotZ: 0, timer: 0, lethal: false },
  // Camera shake
  cameraShake: { intensity: 0, timer: 0 },
  // Post-processing ref
  bloomPass: null,
  // Environment map
  envCubeTexture: null,
  envCanvases: null,
  // Sky dome
  skyDome: null,
  skyDomeMaterial: null,
  starField: null,
  starMaterial: null,
  sunMesh: null,
  moonMesh: null,
  // Post-processing passes
  colorPass: null,
  smaaPass: null,
  // Ocean shader
  oceanMaterial: null,
  // Rain
  rainPoints: null,
  rainActive: false,
  rainToggleTimer: 0,
  // Tire smoke
  tireSmokeParticles: [],
  // Kill tracking for wanted escalation
  killCount: 0,
  policeKilled: 0,
  // Heavy forces
  helicopter: null,
  tanks: [],
  tankShells: [],
  heliMissiles: [],
  // Road material refs for rain toggle
  roadMaterial: null,
  puddleMaterial: null,
  // Restaurant seats
  restaurantSeats: [],
  // Gang system
  gangNpcs: [],
  gangBullets: [],
  // Performance optimization
  bulbMat: null,
  spatialGrid: null,
  mergedMeshes: [],
  grassInstances: [],
};
